name: Scan
on: 
  push:
    branches:
      - 'v[0-9]+.[0-9]+'

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    if:  ${{!startsWith(github.event.head_commit.message, '#NORUN')}}  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-report.txt'
          severity: 'HIGH,CRITICAL'

      - name: Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_TITLE: Scan failed
          SLACK_MESSAGE: |
            Failed trivy scan,see uploaded report
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}

      - uses: MeilCli/slack-upload-file@v3
        with:
            slack_token: ${{secrets.SLACK_TOKEN}}
            channel_id: ${{secrets.SLACK_CHANNEL_ID}}
            file_path: 'trivy-report.txt'
            initial_comment: 'Scan report by Phyo Khant Ko'
      - run: exit 1