name: Build and Push
on: push
jobs:
  CICD:
    name: CICD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-report.txt'
          severity: 'CRITICAL'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      
      - name: Build and push
        uses: prompt/actions-commit-hash@v3
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: g0diaz/go-fortune:${{github.sha}}

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Sign image with a key
        run:  |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY g0diaz/go-fortune:${{github.sha}}
        env:
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}

      - name: Testing
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_TITLE: Image build and signed
            SLACK_MESSAGE: |
              Name: Phyo Khant Ko
              Matriculation: A0287271X
              Email: <mailto:e1285217@u.nus.edu | e1285217@u.nus.edu>
              Git: <https://github.com/g0diaz/CICD>
              Image: 
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 