name: CICD
on: 
  push:
    branches:
      - 'v[0-9]+.[0-9]+'


jobs:
  Complete_Process:
    name: Complete Process
    runs-on: ubuntu-latest
    env:
      FLOW: Completed
    if:  ${{!startsWith(github.event.head_commit.message, '#NORUN')}}  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Complete Process
        id: complete_process
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-report.txt'
          severity: 'CRITICAL'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.2.0'

      - name: Check install!
        run: cosign version
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0   

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: g0diaz/go-fortune
          tags: type=sha,format=long

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      
      - name: Build and push 
        uses: docker/build-push-action@v4.0.0
        id: build-and-push
        with:
          push: true
          tags: ${{steps.docker_meta.outputs.tags}}

      - name: Sign image with a key
        run:  |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
        env:
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          TAGS: ${{steps.docker_meta.outputs.tags}}
          DIGEST: ${{steps.build-and-push.outputs.digest}}

      - name: Notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_TITLE: Image build and signed
            SLACK_MESSAGE: |
              Name: Phyo Khant Ko
              Matriculation: A0287271X
              Email: <mailto:e1285217@u.nus.edu | e1285217@u.nus.edu>
              Git: <https://github.com/g0diaz/ADLC3CA>
              Image: <https://hub.docker.com/repository/docker/g0diaz/go-fortune/general>
            SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}

  Failed_Process:
    name: Failed Process
    runs-on: ubuntu-latest
    env:
      FLOW: Failed
    if:  ${{!startsWith(github.event.head_commit.message, '#NORUN')}}  
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Failed Process
        id: failed_process
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-report.txt'
          severity: 'HIGH,CRITICAL'

      - name: Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_TITLE: Scan failed
          SLACK_MESSAGE: |
            Failed trivy scan,see uploaded report
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}

      - uses: MeilCli/slack-upload-file@v3
        with:
            slack_token: ${{secrets.SLACK_TOKEN}}
            channel_id: ${{secrets.SLACK_CHANNEL_ID}}
            file_path: 'trivy-report.txt'
            initial_comment: 'Scan report by Phyo Khant Ko'
      - run: exit 1
