on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Testing
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_MESSAGE: |
          Luke
          Bobo
          <mailto:e1285217@u.nus.edu | e1285217@u.nus.edu>
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        